// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4pP4OqCMD1MUsEKE5SttQTr12chnWwuM',
    appId: '1:4357235401:web:d882038875a4ee3a462318',
    messagingSenderId: '4357235401',
    projectId: 'afro-united-23c8e',
    authDomain: 'afro-united-23c8e.firebaseapp.com',
    storageBucket: 'afro-united-23c8e.appspot.com',
    measurementId: 'G-72M70K4NCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs2ogLyMJY-1Z_kpQ5v95vhM-48nbdGDQ',
    appId: '1:4357235401:android:94f0453178d8a615462318',
    messagingSenderId: '4357235401',
    projectId: 'afro-united-23c8e',
    storageBucket: 'afro-united-23c8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1qH3c9IFMJ2kvVkseFZ1p_thbCru4Sdc',
    appId: '1:4357235401:ios:d1d20b4fdcdbc44c462318',
    messagingSenderId: '4357235401',
    projectId: 'afro-united-23c8e',
    storageBucket: 'afro-united-23c8e.appspot.com',
    androidClientId: '4357235401-239i148med1ci475d7rqrqotjras32m5.apps.googleusercontent.com',
    iosClientId: '4357235401-csvtvnecsrmn8rk1telcvjsbflojghcj.apps.googleusercontent.com',
    iosBundleId: 'com.renewash.app',
  );
}
